# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminTests1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminTests1(object):
    def setupUi(self, AdminTests1):
        AdminTests1.setObjectName("AdminTests1")
        AdminTests1.resize(423, 389)
        self.label = QtWidgets.QLabel(AdminTests1)
        self.label.setGeometry(QtCore.QRect(120, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(33)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(AdminTests1)
        self.pushButton.setGeometry(QtCore.QRect(130, 160, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AdminTests1)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 280, 151, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(AdminTests1)
        self.label_2.setGeometry(QtCore.QRect(10, 330, 401, 51))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(AdminTests1)
        self.lineEdit.setGeometry(QtCore.QRect(60, 120, 311, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(AdminTests1)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(AdminTests1)
        self.pushButton_3.setGeometry(QtCore.QRect(130, 220, 151, 51))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(AdminTests1)
        QtCore.QMetaObject.connectSlotsByName(AdminTests1)

    def retranslateUi(self, AdminTests1):
        _translate = QtCore.QCoreApplication.translate
        AdminTests1.setWindowTitle(_translate("AdminTests1", "Для админа: Тесты"))
        self.label.setText(_translate("AdminTests1", "Тесты"))
        self.pushButton.setText(_translate("AdminTests1", "Добавить"))
        self.pushButton_2.setText(_translate("AdminTests1", "Назад"))
        self.label_2.setText(_translate("AdminTests1", "Убедитесь, что вопросы в тесте составлены таким образом:\"вопрос\";\"ответ\""))
        self.label_3.setText(_translate("AdminTests1", "\"Название теста[Номер класса]\".txt"))
        self.pushButton_3.setText(_translate("AdminTests1", "Открыть"))
