# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminClasses.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminClasses(object):
    def setupUi(self, AdminClasses):
        AdminClasses.setObjectName("AdminClasses")
        AdminClasses.resize(713, 550)
        self.label = QtWidgets.QLabel(AdminClasses)
        self.label.setGeometry(QtCore.QRect(20, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AdminClasses)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(AdminClasses)
        self.comboBox.setGeometry(QtCore.QRect(260, 30, 241, 31))
        self.comboBox.setObjectName("comboBox")
        self.tableWidget = QtWidgets.QTableWidget(AdminClasses)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 681, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(AdminClasses)
        self.pushButton.setGeometry(QtCore.QRect(520, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AdminClasses)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 490, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AdminClasses)
        QtCore.QMetaObject.connectSlotsByName(AdminClasses)

    def retranslateUi(self, AdminClasses):
        _translate = QtCore.QCoreApplication.translate
        AdminClasses.setWindowTitle(_translate("AdminClasses", "Для админа: Ученики"))
        self.label.setText(_translate("AdminClasses", "Ученики"))
        self.label_2.setText(_translate("AdminClasses", "Класс:"))
        self.pushButton.setText(_translate("AdminClasses", "Показать"))
        self.pushButton_2.setText(_translate("AdminClasses", "Назад"))
