# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StudentClass(object):
    def setupUi(self, StudentClass):
        StudentClass.setObjectName("StudentClass")
        StudentClass.resize(594, 344)
        self.label = QtWidgets.QLabel(StudentClass)
        self.label.setGeometry(QtCore.QRect(16, 12, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(StudentClass)
        self.tableWidget.setGeometry(QtCore.QRect(210, 20, 361, 301))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(StudentClass)
        self.pushButton.setGeometry(QtCore.QRect(24, 82, 151, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(StudentClass)
        self.pushButton_2.setGeometry(QtCore.QRect(24, 142, 151, 61))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(StudentClass)
        QtCore.QMetaObject.connectSlotsByName(StudentClass)

    def retranslateUi(self, StudentClass):
        _translate = QtCore.QCoreApplication.translate
        StudentClass.setWindowTitle(_translate("StudentClass", "Мой класс"))
        self.label.setText(_translate("StudentClass", "Мой класс"))
        self.pushButton.setText(_translate("StudentClass", "Показать"))
        self.pushButton_2.setText(_translate("StudentClass", "Назад"))
