# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(238, 173)
        self.pushButton_3 = QtWidgets.QPushButton(AdminWindow)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 90, 181, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(AdminWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 20, 181, 51))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AdminWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "Для админа"))
        self.pushButton_3.setText(_translate("AdminWindow", "Тесты"))
        self.pushButton_2.setText(_translate("AdminWindow", "Журнал"))
